apiVersion: v1
kind: Service
metadata:
  name: dead-letter-rider
  namespace: dead-letter
  labels:
    run: dead-letter-rider
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: dead-letter-rider
