apiVersion: v1
kind: Service
metadata:
  namespace: dead-letter
  name: dead-letter-order
  labels:
    run: dead-letter-order
spec:
  ports:
    - port: 3000
      protocol: TCP
  selector:
    app: dead-letter-order
