apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: dead-letter
  labels:
    app: postgres
data:
  POSTGRES_CONFIG: |
    POSTGRES_DB: POSTGRES_DB
    POSTGRES_USER: POSTGRES_USER
    POSTGRES_PASSWORD: POSTGRES_PASSWORD
