kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume 
  namespace: dead-letter
  labels:
    type: local  
    app: postgres
spec:
  capacity:
    storage: 5Gi 
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim  
  namespace: dead-letter
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 5Gi  
