apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-storage-dead-letter
  namespace: rabbitmq-dead-letter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
