apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-dead-letter
  namespace: rabbitmq-dead-letter
spec:
  selector:
    app: rabbitmq-dead-letter
  ports:
  - name: ampq
    protocol: TCP
    port: 5672
  - name: management-ui
    protocol: TCP
    port: 15672
    targetPort: 15672
